#ifndef _FXI_CHAR_DEV_H
#define _FXI_CHAR_DEV_H

enum RequestTypes {
	FXINONE = 0,
	FXIREAD,
	FXIWRITE
};

#define FXI_BLOCK_SIZE 512
#define FXI_MAX_BLOCKS 128

#define FXI_CHAR_DEV_IOCTL_BASE 0xad0

#define FXI_CHAR_DEV_IOCTL_BLOCK_DONE (FXI_CHAR_DEV_IOCTL_BASE + 1)
#define FXI_CHAR_DEV_IOCTL_IN (FXI_CHAR_DEV_IOCTL_BASE + 2)
#define FXI_CHAR_DEV_IOCTL_OUT1 (FXI_CHAR_DEV_IOCTL_BASE + 3)
#define FXI_CHAR_DEV_IOCTL_OUT2 (FXI_CHAR_DEV_IOCTL_BASE + 4)
#define FXI_CHAR_DEV_IOCTL_PRELOAD (FXI_CHAR_DEV_IOCTL_BASE + 5)
#define FXI_CHAR_DEV_IOCTL_BATCHSIZE (FXI_CHAR_DEV_IOCTL_BASE + 6)
#define FXI_CHAR_DEV_IOCTL_DATACMD (FXI_CHAR_DEV_IOCTL_BASE + 7)
#define FXI_CHAR_DEV_IOCTL_IMPACK (FXI_CHAR_DEV_IOCTL_BASE + 8)
#define FXI_CHAR_DEV_IOCTL_READY (FXI_CHAR_DEV_IOCTL_BASE + 9)
#define FXI_CHAR_DEV_IOCTL_HASDATA (FXI_CHAR_DEV_IOCTL_BASE + 0xa)
#define FXI_CHAR_DEV_IOCTL_DISABLE_POLL (FXI_CHAR_DEV_IOCTL_BASE + 0xb)

#endif
