#ifndef __CCANYSCREEN_MISC_DRIVER_H__
#define __CCANYSCREEN_MISC_DRIVER_H__

enum request_types {
	CC_REQ_NONE = 0,
	CC_REQ_READ,
	CC_REQ_WRITE
};

#define CC_USB_BLOCK_SIZE 512
#define CC_USB_MAX_BLOCKS 128

#define CC_ANYSCREEN_IOCTL_BASE 0xad0

#define CC_ANYSCREEN_IOCTL_BLOCK_DONE (CC_ANYSCREEN_IOCTL_BASE + 1)
#define CC_ANYSCREEN_IOCTL_IN (CC_ANYSCREEN_IOCTL_BASE + 2)
#define CC_ANYSCREEN_IOCTL_OUT1 (CC_ANYSCREEN_IOCTL_BASE + 3)
#define CC_ANYSCREEN_IOCTL_OUT2 (CC_ANYSCREEN_IOCTL_BASE + 4)
#define CC_ANYSCREEN_IOCTL_PRELOAD (CC_ANYSCREEN_IOCTL_BASE + 5)
#define CC_ANYSCREEN_IOCTL_BATCHSIZE (CC_ANYSCREEN_IOCTL_BASE + 6)
#define CC_ANYSCREEN_IOCTL_DATACMD (CC_ANYSCREEN_IOCTL_BASE + 7)
#define CC_ANYSCREEN_IOCTL_IMPACK (CC_ANYSCREEN_IOCTL_BASE + 8)
#define CC_ANYSCREEN_IOCTL_READY (CC_ANYSCREEN_IOCTL_BASE + 9)
#define CC_ANYSCREEN_IOCTL_HASDATA (CC_ANYSCREEN_IOCTL_BASE + 0xa)
#define CC_ANYSCREEN_IOCTL_DISABLE_POLL (CC_ANYSCREEN_IOCTL_BASE + 0xb)

#endif
